name: camera_trap
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pytorch==2.6.0
  - torchvision
  - pytorch-cuda=11.8
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.59.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - markdown==3.8.2
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - open-clip-torch==3.1.0
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.0.0
      - platformdirs==4.3.8
      - prettytable==3.16.0
      - protobuf==6.31.1
      - pybioclip==2.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.34.1
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.55.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3