# Advanced experiment with all features enabled
experiment_name: "advanced_full"

# Model settings
model: "bioclip"
use_peft: true
peft_config:
  method: "lora"
  r: 16
  alpha: 32
  dropout: 0.1

# Training settings
epochs: 50
learning_rate: 0.0001
weight_decay: 0.0001
batch_size: 64
eval_batch_size: 256
optimizer: "AdamW"
scheduler: "CosineAnnealingLR"
scheduler_params:
  T_max: 50
  eta_min: 0.00001

# Loss settings
loss_type: "focal"
loss_params:
  alpha: 1.0
  gamma: 2.0

# Module settings
ood_method: "uncertainty"
ood_params:
  uncertainty_threshold: 0.7
  uncertainty_method: "entropy"

al_method: "active_ft"
al_params:
  selection_ratio: 0.3
  feature_dim: 512

cl_method: "ewc"
cl_params:
  ewc_lambda: 0.4

# Calibration
calibration: true
calibration_params:
  method: "temperature_scaling"

# Pretraining
pretrain: true
pretrain_epochs: 10

# System settings
device: "cuda"
seed: 42
gpu_cleanup: true
