# Baseline experiment configuration
inherit_from: "../dataset.yaml"

experiment:
  name: "baseline"
  output_dir: "logs/baseline"
  device: "cuda"
  seed: 42

model:
  name: "bioclip"
  use_peft: false
  pretrained: true
  freeze_backbone: false

training:
  epochs: 30
  learning_rate: 0.0001
  weight_decay: 0.0001
  batch_size: 128
  eval_batch_size: 512
  optimizer: "AdamW"
  scheduler: "CosineAnnealingLR"
  scheduler_params:
    T_max: 30
    eta_min: 0.00001
  loss_type: "ce"
  gradient_clip: 1.0
  save_interval: 5
  eval_interval: 5

modules:
  ood:
    method: "all"
    enabled: true
  active_learning:
    method: "all" 
    enabled: true
  continual_learning:
    method: "naive-ft"
    enabled: true
  calibration:
    enabled: false

logging:
  use_wandb: false
  log_interval: 100
