# Sample camera configuration for APN_K024
camera: APN_K024
class_names:
  - baboon
  - buffalo
  - duikercommongrey
  - elephant
  - giraffe
  - impala
  - kudu
  - steenbok
  - warthog
  - wildebeestblue
  - zebraburchells

# Data paths (relative to project root or absolute)
train_data_path: "config/data/APN_K024/train.json"
eval_data_path: "config/data/APN_K024/test.json"

# Camera-specific settings
experiment_name: "APN_K024_baseline"
